name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf automake libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          cmake libffi-dev libssl-dev \
          build-essential ccache m4
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33
    
    - name: Build APK with Buildozer
      run: |
        yes | buildozer android debug
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: hsr-automation-apk
        path: bin/*.apk
        retention-days: 30
    
    - name: Display build info
      run: |
        echo "==================================="
        echo "Build completed successfully!"
        echo "==================================="
        ls -lh bin/*.apk || echo "No APK found"
        echo ""
        echo "Download the APK from the Artifacts section above."

